### PR TITLE
Feature/wechat locations

### PR DESCRIPTION
**Pull request by kimenye**
This PR checks in:

- Additional fields in the notification for handling of locations
- Removed unused test

### CODE REVIEW

**Comment by kimenye** [comment]
@muaad or @SirBertly please review this PR

**Comment by SirBertly** [comment]
The new parameters are correct and sufficient tests are included.

**Comment by kimenye** [comment]
@SirBertly you close

**Comment by kimenye** [comment]
@SirBertly You closed without merging the PR. Please merge before closing

**Comment by kimenye** [comment]
I've done it now though.

**Pull request merged**
